name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - python/

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    env:
      GEMS_PATH: /tmp/bundle

    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install tools
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq==3.3.2 -y

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bundle Caching
        id: bundle-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.GEMS_PATH }}
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          bundle config path ${{ env.GEMS_PATH }}
          bundle install --jobs 4 --retry 3

      - name: Build Site
        run: |
          bash tools/build.sh

          if [[ -n $SPEC_TEST ]]; then
            # Bypass the defects of htmlproofer
            bash tools/build.sh -b "" -d "$SPEC_TEST"
          fi          

      - name: Test Site
        run: |
          bash tools/test.sh "$SPEC_TEST"

      - name: Deploy
        run: |
          bash tools/deploy.sh
