on:
  schedule:
    - cron: '0 3 */7 * *'
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  scheduled-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod
      - name: Checkout pylab
        uses: actions/checkout@v2
        with:
          repository: shirlywhirl/pylab
          path: pylab
      - uses: actions/setup-python@v2
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.0.0
      - name: View poetry --help
        run: poetry --help
